### ISSUE TITLE
How to highlight the specific text？

### ISSUE THREAD

**Issue by Jasonwi** [MarMomento/typora-mo-theme#1]
How to highlight the specific text like README picture shows (yellow)
typora version : 0.9.93
OS : windows10 1909
I doubt the version don't support this feature as picture shows blew 
![image](https://user-images.githubusercontent.com/59698185/89115250-c3aa2480-d4b8-11ea-88f9-ab57843e03ed.png)

**Comment by MarMomento** [comment]
Check the Markdown in the preferences Settings to see if the highlight is on.

**Comment by Jasonwi** [comment]
@MarMomento It's worked. thx~
