### ISSUE TITLE
请教更改哪个选项可以改为 typra 默认的字体

### ISSUE THREAD

**Issue by hysencn** [MarMomento/typora-mo-theme#2]
it's very good. ,
这个 theme 很棒, 解决了汉字选字半个字的问题.
小白, 请教更改哪个选项可以改为 typra 默认的字体?
<img width="640" alt="2020-09-02_18-03-56" src="https://user-images.githubusercontent.com/60783595/91968107-bcd83100-ed46-11ea-81f6-d381151ee54c.png">

**Comment by MarMomento** [comment]
谢谢. typora默认的是Github主题,没有提供直接更改字体的快捷方式,不过你可以在"偏好设置"中"打开主题文件夹",找到"mo.css",修改font-family属性

**Comment by hysencn** [comment]
感谢答复, 我找到了:
body {
  font-family: sans-serif, Times, Georgia, serif;
在这里, 把字体更改为sans-serif, 郁闷的是, 半字情况又回来了. 
我再换其他中文字体试试.
