### ISSUE TITLE
导出PDF文件表格横线缺失问题

### ISSUE THREAD

**Issue by LevickCG** [MarMomento/typora-mo-theme#3]
![image](https://user-images.githubusercontent.com/49020840/96331690-f44e3300-1091-11eb-8616-16e6237d04d5.png)
![image](https://user-images.githubusercontent.com/49020840/96331702-0cbe4d80-1092-11eb-97c0-be4de98e2fc0.png)
如图所示。
Win10，typora 0.9.96（beta），mo 1.0.0

**Comment by MarMomento** [comment]
Fixed
